version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: prediapp-frontend:latest
    ports:
      - "5173:80"          # mapea el puerto 80 del contenedor a 5173 en host
    networks:
      - app-network

networks:
  app-network:
    external: true        # la misma red que usas en el backend
